# Generated by Django 5.2.4 on 2025-07-26 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='학번은 영문자 1자와 숫자 6자리여야 합니다. (예: C135195)', regex='^[A-Za-z]\\d{6}$')])),
                ('full_name', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='이름은 한글 2~5자만 입력 가능합니다.', regex='^[가-힣]{2,5}$')])),
                ('entry_year', models.PositiveSmallIntegerField()),
                ('major', models.CharField(max_length=50)),
            ],
        ),
    ]
