# Generated by Django 5.2.4 on 2025-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('total_required', models.IntegerField(default=132)),
                ('major_required', models.IntegerField(default=50)),
                ('general_required', models.IntegerField(default=8)),
                ('drbol_required', models.IntegerField(default=18)),
                ('special_general_required', models.IntegerField(default=3)),
                ('sw_required', models.IntegerField(default=9)),
                ('msc_required', models.IntegerField(default=23)),
                ('major_must_courses', models.TextField(help_text='전공 필수 과목명(콤마 구분)')),
                ('drbol_areas', models.TextField(help_text='드볼 영역 이름(콤마 구분)')),
            ],
            options={
                'unique_together': {('major', 'year')},
            },
        ),
    ]
